[project]
name = "travelagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "fastmcp>=2.12.0",
    "google-generativeai>=0.8.5",
    "mcp>=1.13.1",
]
